project_id = "aggkhetcdjmggqjzelgd"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.app"]
jwt_expiry = 3600
enable_signup = true
enable_anonymous_sign_ins = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[db]
port = 54322

[studio]
enabled = true
port = 54323

# Fixed: renamed from [edge_functions] to [functions]
[functions]

[functions.gemini-ai]
verify_jwt = false

[functions.mistral-ai]
verify_jwt = false

[functions.newsletter-send]
verify_jwt = false

[functions.newsletter-send-email]
verify_jwt = false

[functions.newsletter-send-confirmation]
verify_jwt = false

[functions.newsletter-confirm]
verify_jwt = false

[functions.newsletter-unsubscribe]
verify_jwt = false

[functions.auto-generate-newsletter]
verify_jwt = false

[functions.qa-archive-search]
verify_jwt = false

[functions.rapid-processor]
verify_jwt = false
