import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'de' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation dictionaries
const translations = {
  de: {
    // Header
    'header.title': '📰 LINKIT NEWS',
    
    // Navigation
    'nav.home': 'Home',
    'nav.newsletter': 'Newsletter',
    'nav.student_news': 'Student News',
    'nav.archive': 'Archiv',
    'nav.database': 'Datenbank',
    
    // Main page
    'main.title': '🤖 KI News Digest',
    'main.subtitle': 'Automatische KI- und Data Science News Aggregation mit intelligenter Filterung für relevante Newsletter-Inhalte',
    'main.student_news': 'Top 10 für Studenten anzeigen',
    'main.database': 'KI-News Datenbank durchsuchen',
    'main.refresh': 'News aktualisieren',
    'main.generate_digest': 'Wöchentlichen Digest generieren',
    'main.week': 'KW',
    'main.automatically_updated': 'Automatisch aktualisiert',
    'main.add_article': 'Artikel hinzufügen',
    'main.custom_articles': 'eigene Artikel in der Übersicht',
    'main.no_custom_articles': 'Noch keine eigenen Artikel',
    'main.click_plus_add': 'Klicken Sie auf das + um Artikel hinzuzufügen',
    'main.custom_article_label': 'Eigener Artikel',
    'main.articles_added': 'Artikel hinzugefügt',
    'main.no_news_found': 'Keine Nachrichten für diese Woche gefunden',
    'main.try_again': 'Erneut versuchen',
    'main.rss_debug_test': 'RSS Debug Test',
    'main.gemini_api_test': 'Gemini API Test',
    'main.testing': 'Teste...',
    
    // Student News
    'student.title': 'Top 10 für Studenten',
    'student.subtitle': 'Die relevantesten Tech- und KI-Nachrichten für Studierende - kuratiert und nach Wichtigkeit sortiert',
    'student.back': 'Zurück zur Hauptseite',
    'student.refresh': 'Artikel neu laden',
    'student.most_relevant': 'Relevanteste Artikel',
    'student.articles': 'Artikel',
    'student.updating': 'Aktualisiere...',
    'student.update': 'Aktualisieren',
    'student.no_articles_found': 'Keine studenten-relevanten Artikel gefunden',
    'student.no_articles_desc': 'Momentan sind keine Artikel verfügbar, die unseren Kriterien entsprechen.',
    'student.selection_criteria': 'Auswahlkriterien',
    'student.relevance_filter': 'Relevanz-Filter:',
    'student.ai_tech_topics': '• KI & Technologie-Themen',
    'student.programming_software': '• Programmierung & Software',
    'student.career_education': '• Karriere & Bildung',
    'student.startup_innovation': '• Startup & Innovation',
    'student.evaluation_criteria': 'Bewertungskriterien:',
    'student.news_timeliness': '• Aktualität der Nachrichten',
    'student.student_keywords': '• Studenten-relevante Keywords',
    'student.trusted_sources': '• Vertrauenswürdige Quellen',
    'student.practical_application': '• Praktische Anwendbarkeit',
    
    // Newsletter
    'newsletter.title': 'Newsletter',
    'newsletter.admin_login': 'Admin Login',
    'newsletter.subscribe': 'Newsletter abonnieren',
    'newsletter.subscribe_title': 'KI-Newsletter abonnieren',
    'newsletter.subscribing': 'Wird abonniert...',
    'newsletter.email_label': 'E-Mail-Adresse',
    'newsletter.email_placeholder': 'ihre.email@example.com',
    'newsletter.email_description': 'Wir verwenden Ihre E-Mail-Adresse nur für den Versand des Newsletters.',
    'newsletter.email_invalid': 'Bitte geben Sie eine gültige E-Mail-Adresse ein.',
    'newsletter.subscription_successful': 'Anmeldung erfolgreich!',
    'newsletter.check_email': 'Bitte bestätigen Sie Ihre E-Mail-Adresse über den Link, den wir Ihnen gesendet haben.',
    'newsletter.subscription_error': 'Es ist ein Fehler aufgetreten. Bitte versuchen Sie es später erneut.',
    'newsletter.thank_you': 'Vielen Dank für Ihr Interesse! Sie erhalten bald eine Bestätigungs-E-Mail.',
    'newsletter.already_registered': 'Diese E-Mail ist bereits registriert. Vielen Dank für Ihr Interesse!',
    'newsletter.subscribe_description': 'Erhalten Sie jeden Dienstagmorgen die wichtigsten KI-Nachrichten direkt in Ihrem Postfach.',
    'newsletter.subscribe_button': 'Abonnieren',
    'newsletter.weekly_delivery': 'Wir versenden unseren Newsletter einmal pro Woche.',
    'newsletter.unsubscribe_info': 'Sie können sich jederzeit vom Newsletter abmelden.',
    'newsletter.admin_access': 'Administrator-Zugang',
    
    // Newsletter Management
    'management.title': 'Newsletter-Verwaltung',
    'management.description': 'Verwalten Sie Ihre Newsletter-Einstellungen und versenden Sie Newsletter aus dem Archiv.',
    'management.back_to_subscribe': 'Zurück zum Abonnieren',
    'management.send_tab': 'Newsletter-Versand',
    'management.archive_tab': 'Newsletter-Archiv',
    'management.history_tab': 'Versand-Historie',
    'management.basic_settings': 'Grundeinstellungen',
    'management.newsletter_selection': 'Newsletter-Auswahl',
    'management.preview': 'Vorschau',
    'management.subscribers': 'Abonnenten',
    'management.confirmed_subscribers': 'bestätigte Abonnenten',
    'management.click_load': 'Klicken Sie auf \'Laden\'',
    'management.load': 'Laden',
    'management.loading': 'Lädt...',
    'management.send_time': 'Versandzeitpunkt',
    'management.select_newsletter': 'Bitte wählen Sie einen Newsletter-Inhalt aus dem Archiv aus.',
    'management.newsletter_sent': 'Newsletter wurde an',
    'management.subscribers_processed': 'Abonnenten verarbeitet!',
    'management.send_error': 'Newsletter konnte nicht versendet werden:',
    'management.unknown_error': 'Unbekannter Fehler',
    'management.loading_archive_error': 'Newsletter-Archiv konnte nicht geladen werden.',
    'management.loading_subscribers_error': 'Abonnenten konnten nicht geladen werden.',
    'management.sender_name': 'Absender-Name',
    'management.sender_email': 'Absender-E-Mail',
    'management.subject': 'Newsletter-Betreff',
    'management.selected_content': 'Ausgewählter Newsletter-Inhalt',
    'management.content_placeholder': 'Newsletter-Inhalt wird hier angezeigt...',
    'management.generate_preview': 'Vorschau generieren',
    'management.select_and_preview': 'Bitte wählen Sie einen Newsletter aus und klicken Sie auf \'Vorschau generieren\'.',
    'management.sending': 'Newsletter wird gesendet...',
    'management.send_now': 'Newsletter jetzt senden',
    
    // Archive QA
    'archive.title': 'KI News Digest',
    'archive.search_placeholder': 'Nach Nachrichten suchen...',
    'archive.search': 'Suchen',
    'archive.clear': 'Löschen',
    'archive.footer_title': 'KI News Digest - Newsletter-Archiv Q&A System für Studierende',
    'archive.footer_desc': 'Durchsuchen Sie alle vergangenen Newsletter und stellen Sie Fragen zu KI-Trends und Entwicklungen',
    
    // Interactive Database
    'database.title': 'KI-News Datenbank',
    'database.subtitle': 'Durchsuchen Sie unsere umfangreiche Sammlung von KI- und Tech-Nachrichten',
    'database.search_placeholder': 'Nach Artikeln suchen...',
    'database.filter_by_source': 'Nach Quelle filtern',
    'database.sort_by': 'Sortieren nach',
    'database.all_sources': 'Alle Quellen',
    'database.all_clusters': 'Alle Cluster',
    'database.select_cluster': 'Cluster auswählen',
    'database.date_newest': 'Datum (Neueste zuerst)',
    'database.date_oldest': 'Datum (Älteste zuerst)',
    'database.relevance': 'Nach Relevanz',
    'database.cluster_relevance': 'Nach Cluster-Relevanz',
    'database.by_date': 'Nach Datum',
    'database.search': 'Suchen',
    'database.clear_filters': 'Filter zurücksetzen',
    'database.results_found': 'Ergebnisse gefunden',
    'database.descending': 'Absteigend',
    'database.ascending': 'Aufsteigend',
    'database.cards': 'Karten',
    'database.list': 'Liste',
    'database.no_articles': 'Noch keine Artikel verfügbar',
    'database.no_articles_desc': 'Lade zuerst einige Artikel über die Hauptseite oder verwende den RSS Debug Test.',
    'database.load_articles': 'Artikel laden',
    'database.to_main_page': 'Zur Hauptseite',
    'database.error_loading': 'Fehler beim Laden',
    'database.try_again': 'Erneut versuchen',
    
    // Buttons and Actions
    'button.refresh': 'Aktualisieren',
    'button.load': 'Laden',
    'button.save': 'Speichern',
    'button.cancel': 'Abbrechen',
    'button.close': 'Schließen',
    'button.edit': 'Bearbeiten',
    'button.delete': 'Löschen',
    'button.add': 'Hinzufügen',
    'button.search': 'Suchen',
    'button.clear': 'Löschen',
    'button.apply': 'Anwenden',
    'button.reset': 'Zurücksetzen',
    
    // News Cards and Articles
    'news.read_article': 'Artikel lesen',
    'news.ai_summary': 'KI-Zusammenfassung',
    'news.generating_summary': 'Analysiere echte Inhalte...',
    'news.generate_ai_summary': 'KI-Zusammenfassung basierend auf echtem Artikel',
    'news.no_articles_found': 'Keine Artikel gefunden',
    'news.reload_news': 'Versuchen Sie, die Nachrichten neu zu laden',
    'news.loading_articles': 'Artikel werden geladen...',
    'news.load_news': 'Nachrichten laden',
    'news.load_news_now': 'Nachrichten jetzt laden',
    'news.current_ai_news': 'KI-News Aktuell',
    'news.current_ai_news_desc': 'Aktuelle KI-Nachrichten',
    'news.no_articles_available': 'Keine Artikel verfügbar',
    'news.click_load_news': 'Klicken Sie auf "Nachrichten laden" um KI-News zu laden',
    'news.ensure_rss_active': 'Stellen Sie sicher, dass mindestens eine RSS-Quelle aktiviert ist',
    'news.removed_from_overview': 'Artikel aus der Übersicht entfernt',
    
    // Weekly Digest
    'digest.top_10': 'Top 10',
    'digest.all_articles': 'Alle Artikel',
    'digest.selected_articles': 'ausgewählte Artikel für Newsletter',
    'digest.automatically_selected': 'relevanteste Artikel (automatisch ausgewählt)',
    'digest.selected': 'ausgewählt',
    'digest.week_overview': 'Wochenübersicht:',
    'digest.weeks_available': 'Wochen verfügbar',
    'digest.news_tab': 'Nachrichten',
    'digest.newsletter_tab': 'Newsletter',
    'digest.questions_tab': 'Fragen',
    'digest.selected_short': 'ausgewählt',
    'digest.create_newsletter': 'Newsletter erstellen',
    'digest.regenerate': 'Neu generieren',
    'digest.generating': 'Generiert...',
    
    // Article Selection
    'selection.select_articles': 'Artikel für Newsletter auswählen',
    'selection.articles_selected': 'von',
    'selection.articles_selected_total': 'Artikeln ausgewählt',
    'selection.reset_selection': 'Auswahl zurücksetzen',
    'selection.select_all': 'Alle auswählen',
    'selection.article': 'Artikel',
    'selection.date': 'Datum',
    'selection.source': 'Quelle',
    'selection.unknown': 'Unbekannt',
    'selection.open_article': 'Artikel öffnen',
    'selection.cancel': 'Abbrechen',
    'selection.use_articles': 'Artikel verwenden',
    'selection.confirm': 'Bestätigen',
    'selection.select_top_10': 'Top 10 auswählen',
    'selection.delete_permanently': 'Artikel dauerhaft löschen',
    'selection.select_newsletter_articles': 'Newsletter-Artikel auswählen',
    
    // Database
    'database.interactive_database': 'Interaktive Artikel-Datenbank',
    'database.articles_classified': 'Artikel thematisch klassifiziert',
    'database.articles_displayed': 'angezeigt',
    'database.loading_database': 'Lade Artikeldatenbank...',
    'database.articles_being_classified': 'Artikel werden klassifiziert und sortiert',
    'database.no_articles_found_filter': 'Keine Artikel gefunden',
    'database.try_different_search': 'Versuche eine andere Suche oder entferne Filter',
    'database.reload_page': 'Lade die Seite neu, um Artikel zu laden',
    'database.reload_articles': 'Artikel neu laden',
    'database.total_articles': 'Gesamt Artikel:',
    'database.today': 'Heute:',
    'database.this_week': 'Diese Woche:',
    'database.avg_relevance': 'Ø Relevanz:',
    'database.time_distribution': 'Zeitliche Verteilung',
    
    // Newsletter Archive
    'archive.loading_newsletters': 'Newsletter werden geladen...',
    'archive.no_newsletters_found': 'Keine Newsletter im Archiv gefunden.',
    'archive.auto_saved': 'Newsletter werden automatisch beim Generieren gespeichert.',
    'archive.title_column': 'Titel',
    'archive.date_column': 'Datum',
    'archive.articles_column': 'Artikel',
    'archive.actions_column': 'Aktionen',
    'archive.based_on_articles': 'Basierend auf',
    'archive.top_articles': 'Top-Artikeln der',
    'archive.and_more': 'weitere',
    
    // Loading States
    'loading.ai_news': 'Lade KI-Nachrichten...',
    'loading.collecting_articles': 'Sammle aktuelle News-Artikel...',
    'loading.creating_overview': 'Erstelle Wochenübersicht...',
    'loading.successfully_loaded': 'Erfolgreich geladen!',
    'loading.articles_found': 'Artikel gefunden',
    'loading.loading': 'Lädt...',
    
    // Questions/QA translations
    'qa.newsletter_questions': 'Fragen zum Newsletter',
    'qa.ask_about_articles': 'Stellen Sie Fragen zu den {count} Artikeln {hasContent}',
    'qa.ask_about_articles_content': 'und dem Newsletter-Inhalt',
    'qa.ask_about_articles_only': 'in diesem Newsletter',
    'qa.clear_chat': 'Chat löschen',
    'qa.chat_history': 'Chat-Verlauf',
    'qa.your_question': 'Ihre Frage:',
    'qa.ask_question': 'Frage stellen',
    'qa.analyzing': 'Analysiere...',
    'qa.analyzing_archives': 'Analysiere Archive...',
    'qa.smart_suggestions': 'Intelligente Fragevorschläge:',
    'qa.articles_available': 'Artikel verfügbar',
    'qa.newsletter_content_available': 'Newsletter-Inhalt verfügbar',
    'qa.ask_archives': 'Stellen Sie eine Frage zu den Newsletter-Archiven:',
    'qa.archive_placeholder': 'Z.B. \'Welche KI-Trends wurden in den letzten Monaten diskutiert?\' oder nutzen Sie die Spracheingabe...',
    'qa.newsletter_placeholder': 'Z.B. \'Welche KI-Trends werden im Newsletter diskutiert?\' oder nutzen Sie die Spracheingabe...',
    'qa.article_placeholder': 'Z.B. \'Welche KI-Trends werden in den Artikeln diskutiert?\' oder nutzen Sie die Spracheingabe...',
    'qa.current_suggestions': 'Aktuelle Fragevorschläge:',
    'qa.loading_suggestions': 'Lade aktuelle Fragevorschläge...',
    'qa.based_on_articles': 'Basierend auf {count} Artikeln {content}',
    'qa.reference_newsletters': 'Referenzierte Newsletter:',
    'qa.top_articles_week': 'Top-Artikeln der KW {week}/{year}',
    'qa.companies': 'Unternehmen',
    'qa.technologies': 'Technologien', 
    'qa.last_update': 'Letztes Update',
    'qa.no_current_articles': 'Keine aktuellen Artikel verfügbar - verwende Standard-Fragen',
    'qa.debug_topics': 'Debug: Erkannte Themen',

    // Toast Messages and Notifications
    'toast.new_articles_found': 'neue Artikel gefunden!',
    'toast.no_new_articles': 'Keine neuen Artikel gefunden',
    'toast.article_already_exists': 'Ein Artikel mit dieser URL ist bereits in der lokalen Liste vorhanden',
    'toast.article_added_successfully': 'Artikel erfolgreich hinzugefügt und gespeichert',
    'toast.article_save_error': 'Fehler beim Speichern des Artikels in der Datenbank',
    'toast.loading_error': 'Fehler beim Laden der Nachrichten:',
    'toast.student_news_error': 'Fehler beim Laden der Studenten-relevanten Nachrichten:',
    'toast.no_articles_found_reload': 'Keine Artikel gefunden. Versuche die Seite neu zu laden.',
    'toast.articles_loaded_classified': 'Artikel geladen und nach Relevanz klassifiziert',
    'toast.error_loading_articles': 'Fehler beim Laden der Artikel',
    'toast.articles_for_summary': 'Artikel für die Zusammenfassung ausgewählt',
    'toast.no_newsletter_content': 'Kein Newsletter-Inhalt zum Speichern vorhanden',
    'toast.save_failed': 'Speichern fehlgeschlagen - kein Ergebnis erhalten',
    'toast.newsservice_unavailable': 'NewsService nicht verfügbar',

    // Status Messages
    'status.no_summary_created': 'Noch keine Zusammenfassung erstellt',
    'status.articles_loading': 'Artikel werden geladen...',
    'status.creating': 'Erstellen',
    'status.regenerate': 'Neu',
    'status.saving': 'Speichert...',
    'status.saved': 'Gespeichert',
    'status.save': 'Speichern',

    // Voice Input - German
    'voice.no_speech_detected': 'Keine Sprache erkannt. Versuchen Sie es erneut.',
    'voice.microphone_access_denied': 'Mikrofonzugriff verweigert oder nicht verfügbar.',
    'voice.microphone_permission_denied': 'Mikrofonberechtigung verweigert. Bitte erlauben Sie den Mikrofonzugriff.',
    'voice.microphone_access_browser': 'Mikrofonzugriff verweigert. Bitte erlauben Sie den Zugriff in Ihren Browser-Einstellungen.',

    // RSS and Custom Articles - German
    'rss.sources': 'RSS-Quellen',
    'rss.manage_sources': 'RSS-Quellen verwalten und neue hinzufügen',
    'rss.no_sources': 'Keine RSS-Quellen vorhanden. Fügen Sie eine hinzu.',
    'custom.add_article': 'Eigenen Artikel hinzufügen',
    'custom.add_article_button': 'Artikel hinzufügen',

    // Common
    'common.loading': 'Lädt',
    'common.error': 'Fehler',
    'common.success': 'Erfolgreich',
    'common.back': 'Zurück',
    'common.read_more': 'Mehr lesen',
    'common.source': 'Quelle',
    'common.published': 'Veröffentlicht',
    'common.tags': 'Tags',
    'common.language': 'Sprache',
    'common.language_toggle': 'Sprache wechseln',
    'common.no_results': 'Keine Ergebnisse',
    'common.show_more': 'Mehr anzeigen',
    'common.show_less': 'Weniger anzeigen',
    'common.page': 'Seite',
    'common.of': 'von',
    'common.total': 'Gesamt',
    'common.items': 'Elemente',
  },
  en: {
    // Header
    'header.title': '📰 LINKIT NEWS',
    
    // Navigation
    'nav.home': 'Home',
    'nav.newsletter': 'Newsletter',
    'nav.student_news': 'Student News',
    'nav.archive': 'Archive',
    'nav.database': 'Database',
    
    // Main page
    'main.title': '🤖 AI News Digest',
    'main.subtitle': 'Automatic AI & Data Science News Aggregation with intelligent filtering for relevant newsletter content',
    'main.student_news': 'Show Top 10 for Students',
    'main.database': 'Browse AI News Database',
    'main.refresh': 'Refresh News',
    'main.generate_digest': 'Generate Weekly Digest',
    'main.week': 'Week',
    'main.automatically_updated': 'Automatically updated',
    'main.add_article': 'Add Article',
    'main.custom_articles': 'custom articles in overview',
    'main.no_custom_articles': 'No custom articles yet',
    'main.click_plus_add': 'Click the + to add articles',
    'main.custom_article_label': 'Custom Article',
    'main.articles_added': 'articles added',
    'main.no_news_found': 'No news found for this week',
    'main.try_again': 'Try again',
    'main.rss_debug_test': 'RSS Debug Test',
    'main.gemini_api_test': 'Gemini API Test',
    'main.testing': 'Testing...',
    
    // Student News
    'student.title': 'Top 10 for Students',
    'student.subtitle': 'The most relevant tech and AI news for students - curated and sorted by importance',
    'student.back': 'Back to Main Page',
    'student.refresh': 'Reload Articles',
    'student.most_relevant': 'Most Relevant Articles',
    'student.articles': 'Articles',
    'student.updating': 'Updating...',
    'student.update': 'Update',
    'student.no_articles_found': 'No student-relevant articles found',
    'student.no_articles_desc': 'Currently no articles available that meet our criteria.',
    'student.selection_criteria': 'Selection Criteria',
    'student.relevance_filter': 'Relevance Filter:',
    'student.ai_tech_topics': '• AI & Technology Topics',
    'student.programming_software': '• Programming & Software',
    'student.career_education': '• Career & Education',
    'student.startup_innovation': '• Startup & Innovation',
    'student.evaluation_criteria': 'Evaluation Criteria:',
    'student.news_timeliness': '• News Timeliness',
    'student.student_keywords': '• Student-relevant Keywords',
    'student.trusted_sources': '• Trusted Sources',
    'student.practical_application': '• Practical Application',
    
    // Newsletter
    'newsletter.title': 'Newsletter',
    'newsletter.admin_login': 'Admin Login',
    'newsletter.subscribe': 'Subscribe to Newsletter',
    'newsletter.subscribe_title': 'Subscribe to AI Newsletter',
    'newsletter.subscribing': 'Subscribing...',
    'newsletter.email_label': 'Email Address',
    'newsletter.email_placeholder': 'your.email@example.com',
    'newsletter.email_description': 'We only use your email address to send you the newsletter.',
    'newsletter.email_invalid': 'Please enter a valid email address.',
    'newsletter.subscription_successful': 'Subscription Successful!',
    'newsletter.check_email': 'Please confirm your email address using the link we sent you.',
    'newsletter.subscription_error': 'An error occurred. Please try again later.',
    'newsletter.thank_you': 'Thank you for your interest! You will receive a confirmation email soon.',
    'newsletter.already_registered': 'This email is already registered. Thank you for your interest!',
    'newsletter.subscribe_description': 'Receive the most important AI news every Tuesday morning directly in your inbox.',
    'newsletter.subscribe_button': 'Subscribe',
    'newsletter.weekly_delivery': 'We send our newsletter once a week.',
    'newsletter.unsubscribe_info': 'You can unsubscribe from the newsletter at any time.',
    'newsletter.admin_access': 'Administrator Access',
    
    // Newsletter Management
    'management.title': 'Newsletter Management',
    'management.description': 'Manage your newsletter settings and send newsletters from the archive.',
    'management.back_to_subscribe': 'Back to Subscribe',
    'management.send_tab': 'Newsletter Sending',
    'management.archive_tab': 'Newsletter Archive',
    'management.history_tab': 'Sending History',
    'management.basic_settings': 'Basic Settings',
    'management.newsletter_selection': 'Newsletter Selection',
    'management.preview': 'Preview',
    'management.subscribers': 'Subscribers',
    'management.confirmed_subscribers': 'confirmed subscribers',
    'management.click_load': 'Click \'Load\'',
    'management.load': 'Load',
    'management.loading': 'Loading...',
    'management.send_time': 'Send Time',
    'management.select_newsletter': 'Please select a newsletter content from the archive.',
    'management.newsletter_sent': 'Newsletter was sent to',
    'management.subscribers_processed': 'subscribers processed!',
    'management.send_error': 'Newsletter could not be sent:',
    'management.unknown_error': 'Unknown error',
    'management.loading_archive_error': 'Newsletter archive could not be loaded.',
    'management.loading_subscribers_error': 'Subscribers could not be loaded.',
    'management.sender_name': 'Sender Name',
    'management.sender_email': 'Sender Email',
    'management.subject': 'Newsletter Subject',
    'management.selected_content': 'Selected Newsletter Content',
    'management.content_placeholder': 'Newsletter content will be displayed here...',
    'management.generate_preview': 'Generate Preview',
    'management.select_and_preview': 'Please select a newsletter and click \'Generate Preview\'.',
    'management.sending': 'Newsletter is being sent...',
    'management.send_now': 'Send Newsletter Now',
    
    // Archive QA
    'archive.title': 'AI News Digest',
    'archive.search_placeholder': 'Search for news...',
    'archive.search': 'Search',
    'archive.clear': 'Clear',
    'archive.footer_title': 'AI News Digest - Newsletter Archive Q&A System for Students',
    'archive.footer_desc': 'Browse all past newsletters and ask questions about AI trends and developments',
    
    // Interactive Database
    'database.title': 'AI News Database',
    'database.subtitle': 'Browse our extensive collection of AI and tech news',
    'database.search_placeholder': 'Search for articles...',
    'database.filter_by_source': 'Filter by source',
    'database.sort_by': 'Sort by',
    'database.all_sources': 'All Sources',
    'database.all_clusters': 'All Clusters',
    'database.select_cluster': 'Select Cluster',
    'database.date_newest': 'Date (Newest first)',
    'database.date_oldest': 'Date (Oldest first)',
    'database.relevance': 'By Relevance',
    'database.cluster_relevance': 'By Cluster Relevance',
    'database.by_date': 'By Date',
    'database.search': 'Search',
    'database.clear_filters': 'Clear Filters',
    'database.results_found': 'results found',
    'database.descending': 'Descending',
    'database.ascending': 'Ascending',
    'database.cards': 'Cards',
    'database.list': 'List',
    'database.no_articles': 'No articles available yet',
    'database.no_articles_desc': 'Load some articles first via the main page or use the RSS Debug Test.',
    'database.load_articles': 'Load Articles',
    'database.to_main_page': 'To Main Page',
    'database.error_loading': 'Error Loading',
    'database.try_again': 'Try Again',
    
    // Buttons and Actions
    'button.refresh': 'Refresh',
    'button.load': 'Load',
    'button.save': 'Save',
    'button.cancel': 'Cancel',
    'button.close': 'Close',
    'button.edit': 'Edit',
    'button.delete': 'Delete',
    'button.add': 'Add',
    'button.search': 'Search',
    'button.clear': 'Clear',
    'button.apply': 'Apply',
    'button.reset': 'Reset',
    
    // News Cards and Articles
    'news.read_article': 'Read Article',
    'news.ai_summary': 'AI Summary',
    'news.generating_summary': 'Analyzing real content...',
    'news.generate_ai_summary': 'AI summary based on real article',
    'news.no_articles_found': 'No articles found',
    'news.reload_news': 'Try reloading the news',
    'news.loading_articles': 'Loading articles...',
    'news.load_news': 'Load News',
    'news.load_news_now': 'Load News Now',
    'news.current_ai_news': 'Current AI News',
    'news.current_ai_news_desc': 'Current AI News',
    'news.no_articles_available': 'No articles available',
    'news.click_load_news': 'Click "Load News" to load AI news',
    'news.ensure_rss_active': 'Make sure at least one RSS source is active',
    'news.removed_from_overview': 'Article removed from overview',
    
    // Weekly Digest
    'digest.top_10': 'Top 10',
    'digest.all_articles': 'All Articles',
    'digest.selected_articles': 'selected articles for newsletter',
    'digest.automatically_selected': 'most relevant articles (automatically selected)',
    'digest.selected': 'selected',
    'digest.week_overview': 'Week Overview:',
    'digest.weeks_available': 'weeks available',
    'digest.news_tab': 'News',
    'digest.newsletter_tab': 'Newsletter',
    'digest.questions_tab': 'Questions',
    'digest.selected_short': 'selected',
    'digest.create_newsletter': 'Create Newsletter',
    'digest.regenerate': 'Regenerate',
    'digest.generating': 'Generating...',
    
    // Article Selection
    'selection.select_articles': 'Select Articles for Newsletter',
    'selection.articles_selected': 'of',
    'selection.articles_selected_total': 'articles selected',
    'selection.reset_selection': 'Reset Selection',
    'selection.select_all': 'Select All',
    'selection.article': 'Article',
    'selection.date': 'Date',
    'selection.source': 'Source',
    'selection.unknown': 'Unknown',
    'selection.open_article': 'Open Article',
    'selection.cancel': 'Cancel',
    'selection.use_articles': 'Use Articles',
    'selection.confirm': 'Confirm',
    'selection.select_top_10': 'Select Top 10',
    'selection.delete_permanently': 'Delete article permanently',
    'selection.select_newsletter_articles': 'Select Newsletter Articles',
    
    // Database
    'database.interactive_database': 'Interactive Article Database',
    'database.articles_classified': 'articles thematically classified',
    'database.articles_displayed': 'displayed',
    'database.loading_database': 'Loading article database...',
    'database.articles_being_classified': 'Articles are being classified and sorted',
    'database.no_articles_found_filter': 'No articles found',
    'database.try_different_search': 'Try a different search or remove filters',
    'database.reload_page': 'Reload the page to load articles',
    'database.reload_articles': 'Reload Articles',
    'database.total_articles': 'Total Articles:',
    'database.today': 'Today:',
    'database.this_week': 'This Week:',
    'database.avg_relevance': 'Avg Relevance:',
    'database.time_distribution': 'Time Distribution',
    
    // Newsletter Archive
    'archive.loading_newsletters': 'Loading newsletters...',
    'archive.no_newsletters_found': 'No newsletters found in archive.',
    'archive.auto_saved': 'Newsletters are automatically saved when generated.',
    'archive.title_column': 'Title',
    'archive.date_column': 'Date',
    'archive.articles_column': 'Articles',
    'archive.actions_column': 'Actions',
    'archive.based_on_articles': 'Based on',
    'archive.top_articles': 'top articles of',
    'archive.and_more': 'more',
    
    // Loading States
    'loading.ai_news': 'Loading AI news...',
    'loading.collecting_articles': 'Collecting current news articles...',
    'loading.creating_overview': 'Creating weekly overview...',
    'loading.successfully_loaded': 'Successfully loaded!',
    'loading.articles_found': 'articles found',
    'loading.loading': 'Loading...',
    
    // Questions/QA translations - English
    'qa.newsletter_questions': 'Newsletter Questions',
    'qa.ask_about_articles': 'Ask questions about the {count} articles {hasContent}',
    'qa.ask_about_articles_content': 'and newsletter content',
    'qa.ask_about_articles_only': 'in this newsletter',
    'qa.clear_chat': 'Clear Chat',
    'qa.chat_history': 'Chat History',
    'qa.your_question': 'Your Question:',
    'qa.ask_question': 'Ask Question',
    'qa.analyzing': 'Analyzing...',
    'qa.analyzing_archives': 'Analyzing Archives...',
    'qa.smart_suggestions': 'Smart Question Suggestions:',
    'qa.articles_available': 'articles available',
    'qa.newsletter_content_available': 'newsletter content available',
    'qa.ask_archives': 'Ask a question about the newsletter archives:',
    'qa.archive_placeholder': 'E.g. \'Which AI trends were discussed in recent months?\' or use voice input...',
    'qa.newsletter_placeholder': 'E.g. \'Which AI trends are discussed in the newsletter?\' or use voice input...',
    'qa.article_placeholder': 'E.g. \'Which AI trends are discussed in the articles?\' or use voice input...',
    'qa.current_suggestions': 'Current Question Suggestions:',
    'qa.loading_suggestions': 'Loading current question suggestions...',
    'qa.based_on_articles': 'Based on {count} articles {content}',
    'qa.reference_newsletters': 'Referenced Newsletters:',
    'qa.top_articles_week': 'top articles of week {week}/{year}',
    'qa.companies': 'Companies',
    'qa.technologies': 'Technologies', 
    'qa.last_update': 'Last Update',
    'qa.no_current_articles': 'No current articles available - using standard questions',
    'qa.debug_topics': 'Debug: Detected Topics',

    // Toast Messages and Notifications - English
    'toast.new_articles_found': 'new articles found!',
    'toast.no_new_articles': 'No new articles found',
    'toast.article_already_exists': 'An article with this URL already exists in the local list',
    'toast.article_added_successfully': 'Article successfully added and saved',
    'toast.article_save_error': 'Error saving article to database',
    'toast.loading_error': 'Error loading news:',
    'toast.student_news_error': 'Error loading student-relevant news:',
    'toast.no_articles_found_reload': 'No articles found. Try reloading the page.',
    'toast.articles_loaded_classified': 'articles loaded and classified by relevance',
    'toast.error_loading_articles': 'Error loading articles',
    'toast.articles_for_summary': 'articles selected for summary',
    'toast.no_newsletter_content': 'No newsletter content available to save',
    'toast.save_failed': 'Save failed - no result received',
    'toast.newsservice_unavailable': 'NewsService unavailable',

    // Status Messages - English
    'status.no_summary_created': 'No summary created yet',
    'status.articles_loading': 'Loading articles...',
    'status.creating': 'Creating',
    'status.regenerate': 'Regenerate',
    'status.saving': 'Saving...',
    'status.saved': 'Saved',
    'status.save': 'Save',

    // Voice Input - English
    'voice.no_speech_detected': 'No speech detected. Please try again.',
    'voice.microphone_access_denied': 'Microphone access denied or unavailable.',
    'voice.microphone_permission_denied': 'Microphone permission denied. Please allow microphone access.',
    'voice.microphone_access_browser': 'Microphone access denied. Please allow access in your browser settings.',

    // RSS and Custom Articles - English
    'rss.sources': 'RSS Sources',
    'rss.manage_sources': 'Manage RSS sources and add new ones',
    'rss.no_sources': 'No RSS sources available. Add one.',
    'custom.add_article': 'Add Custom Article',
    'custom.add_article_button': 'Add Article',

    // Common
    'common.loading': 'Loading',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.back': 'Back',
    'common.read_more': 'Read more',
    'common.source': 'Source',
    'common.published': 'Published',
    'common.tags': 'Tags',
    'common.language': 'Language',
    'common.language_toggle': 'Switch Language',
    'common.no_results': 'No results',
    'common.show_more': 'Show more',
    'common.show_less': 'Show less',
    'common.page': 'Page',
    'common.of': 'of',
    'common.total': 'Total',
    'common.items': 'items',
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'de';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}; 