// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aggkhetcdjmggqjzelgd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFnZ2toZXRjZGptZ2dxanplbGdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0Mjk4NjUsImV4cCI6MjA2MjAwNTg2NX0.XW9bhjKknGFfgkIW9poUsTM8h_GwFZCWz0duZvT4bJ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
