// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nywmylszhzifqovfnbva.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im55d215bHN6aHppZnFvdmZuYnZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwNzg5MTcsImV4cCI6MjA2MTY1NDkxN30.NB2ZX6dN7IKcoD8xbb9BLeiaSDo73MhO3MkUwYuvcUQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);